#!/usr/bin/python
import re

import os
import sys
import setup
import shutil
import socket
import subprocess


setup.pre_install()

from charmhelpers.core import hookenv
from charmhelpers.core import host

def node_puppet_create(myid, zkhosts):
    host_name = subprocess.check_output(["hostname"])
    host_name = host_name.strip()
    fd = open("node.pp","w")
    node_def = """
node %s {\n
    hadoop-zookeeper::install {"%s":\n
    }\n
    ->\n
    hadoop-zookeeper::configure {"%s":\n
        myid => "%d",\n
        ensemble => %s\n
    }\n
    ->\n
    hadoop-zookeeper::start {"%s":\n
    }\n
}
""" %(host_name,
      host_name,
      host_name,
      myid,
      zkhosts,
      host_name)
    fd.write("%s" % node_def)
    fd.close()

def install_zookeeper():
    config = hookenv.config()
    zkhosts = []
    # create temporary directory
    os.makedirs("/tmp/midonet", 0755)
    os.chdir("/tmp/midonet")

    # the first cluster node myst have my_id 1
    zkid = 1

    # construct the ensemble string
    host_name =  subprocess.check_output("hostname", shell=True)
    host_ip = socket.gethostbyname(host_name.strip())
    hostips = config['zookeeper_hosts']
    ips = list(hostips.split(' '))
    for ip in sorted(ips):
        zkhosts.append("%s:2888:3888" %str(ip))
        if ip == host_ip:
            my_id = zkid
        zkid = zkid + 1

    #create the node.pp for puppet apply
    node_puppet_create(my_id, zkhosts)
    repo = config['midonet_puppet_modules']
    branch = config['midonet_puppet_modules_branch']
    git_cmd = "sudo git clone %s --branch %s" %(repo, branch)
    subprocess.check_output(git_cmd, shell=True)
    MODULEPATH = os.getcwd()+'/orizuru/puppet/modules'
    PUPPET_NODE_DEFINITION = os.getcwd()+'/node.pp'

    # run the puppet apply command
    command = "puppet apply --verbose --show_diff --modulepath=%s %s" %(MODULEPATH, PUPPET_NODE_DEFINITION)
    output = subprocess.check_output(command, shell=True)
    os.chdir("/tmp")
    # delete temporary directory midonet 
    shutil.rmtree("midonet")

def install():
    hookenv.log('Installing midonet-zookeeper')
    install_zookeeper()

if __name__ == "__main__":
    install()
