#!/usr/bin/python
#
# Copyright (c) 2015 Midokura SARL, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
from configobj import ConfigObj
from charmhelpers.core import hookenv

from charmhelpers.core.hookenv import (
    Hooks,
    config,
    relation_get,
    relation_ids,
    relation_set,
    related_units,
    unit_get,
)

def relation_changed():
    hookenv.log('relation changed with zookeeper')
    config = hookenv.config()
    zookeeper_hosts = relation_get('zookeeper_hosts')
    if zookeeper_hosts:
        zconfig = ConfigObj()
        zconfig.filename = "zoo.cfg"
        zconfig['zookeeper_hosts'] = zookeeper_hosts
        zconfig.write()
    
if __name__ == "__main__":
    relation_changed()
