#
# Copyright (c) 2015 Midokura SARL, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
options:
  debug:
    type: string
    default: "True"
    description: "enable debug"
  admin_token:
    type: string
    default: "dS3BMbJgrqbKZKKfx7qkPCYwn5F3GBqF2BNnRgJMsSX2RfwNMkBprdkCw44PzVJY"
    description: "admin token from keystone"
  midonet_puppet_modules:
    type: string
    default: "https://github.com/midonet/orizuru.git"
    description: "Repository for midonet"
  midonet_puppet_modules_branch:
    type: string
    default: "master" 
    description: "Branch on Repository"
  keystone_ip:
    type: string
    default: "192.168.8.83" 
    description: "Keystone server IP address"
  midonet_api_ip:
    type: string
    default: "127.0.0.1" 
    description: "Midonet API IP"
  midonet_api_outer_ip:
    type: string
    default: "192.168.8.84" 
    description: "Midonet API IP"
  zookeeper_hosts:
    type: string
    default: "None"
    description: "get the zookeeper ip's from relation-changed"
