#!/usr/bin/python
#
# Copyright (c) 2015 Midokura SARL, All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import re
import os
import sys
import setup
import shutil
import socket
import subprocess
import tempfile

from charmhelpers.core import hookenv

from charmhelpers.core.hookenv import (
    Hooks,
    config,
    relation_get,
    relation_ids,
    relation_set,
    related_units,
    unit_get,
)

def create_puppet_node_manifest(zk_ips):
    """
    Creates and returns the puppet node manifest as a string.
    """
    
    zkhosts = []
    host_name = subprocess.check_output(["hostname"])
    host_name = host_name.strip()
    config = hookenv.config()
    # list the zookeeper server ips
    hostips = zk_ips
    ips = list(hostips.split(' '))
    for ip in sorted(ips):
        zkhosts.append("%s" %str(ip))
   
    return """

node "%s" {
    midonet_api::configure {"%s":
        keystone_admin_token => "%s",
        keystone_service_host => "%s",
        rest_api_base_url => "http://%s:8080/midonet-api",
        zookeeper_hosts => "%s"
    }
    ->
    midonet_api::start {"%s":
    }
}
""" % (
        host_name,
        host_name,
        config['admin_token'],
        config['keystone_ip'],
        config['midonet_api_outer_ip'],
        ",".join(zkhosts),
        host_name
      )

def run_puppet_node_manifest(manifest, modules, branch):
    """
    Run the manifest with the modules from github and a certain branch.
    """

    temp = tempfile.NamedTemporaryFile()

    temp.write(manifest)

    temp.seek(0)

    try:
        subprocess.check_output("""

set -e

NODE_MANIFEST="%s"

PUPPET_MODULE_URL="%s"

PUPPET_MODULE_BRANCH="%s"

TMPDIR="/tmp/midonet-charms/$(mktemp -d -u)"

mkdir -pv "${TMPDIR}"

cd "${TMPDIR}"

git clone "${PUPPET_MODULE_URL}" --branch "${PUPPET_MODULE_BRANCH}"

cd "${TMPDIR}/orizuru/puppet/modules"

puppet apply --verbose --debug --show_diff --modulepath=$(pwd) "${NODE_MANIFEST}"

cd

rm -rfv "${TMPDIR}"

sync

""" % (temp.name, modules, branch), shell=True)
    except subprocess.CalledProcessError:
        hookenv.log('Error applying the puppet module')
        sys.exit(1)

    temp.close()

    return

def puppet_config_apply(zookeeper_hosts):
 
    config = hookenv.config()

    manifest = create_puppet_node_manifest(zookeeper_hosts)

    run_puppet_node_manifest(manifest, config['midonet_puppet_modules'], config['midonet_puppet_modules_branch'])


def relation_changed():
    hookenv.log('midonet-api relation  changed with zookeeper')
    config = hookenv.config()
    zookeeper_hosts = relation_get('zookeeper_hosts')
    if zookeeper_hosts:
        puppet_config_apply(zookeeper_hosts)

if __name__ == "__main__":
    relation_changed()

