options:
  openstack-origin:
    default: cloud:trusty-juno
    type: string
    description: |
      Repository from which to install.  May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Cloud Archive release pocket.

      Supported Cloud Archive sources include: cloud:precise-folsom,
      cloud:precise-folsom/updates, cloud:precise-folsom/staging,
      cloud:precise-folsom/proposed.

      Note that updating this setting to a source that is known to
      provide a later version of OpenStack will trigger a software
      upgrade.
  rabbit-user:
    default: neutron
    type: string
    description: Username used to access rabbitmq queue
  rabbit-vhost:
    default: openstack
    type: string
    description: Rabbitmq vhost
  database-user:
    default: neutron
    type: string
    description: Username for Neutron database access (if enabled)
  database:
    default: neutron
    type: string
    description: Database name for Neutron (if enabled)
  use-syslog:
    type: boolean
    default: False
    description: |
      If set to True, supporting services will log to syslog.
  region:
    default: RegionOne
    type: string
    description: OpenStack Region
  neutron-security-groups:
    type: boolean
    default: False
    description: |
      Use quantum for security group management.
  neutron-external-network:
    type: string
    default: ext_net
    description: Name of the external network for floating IP addresses provided by Neutron.
  neutron-plugin:
    default: midonet
    type: string
    description: |
      Neutron plugin to use for network management; supports
      .
        ovs - OpenvSwitch Plugin
        nsx - VMWare NSX
        midonet - Midokura MidoNet
      .
  overlay-network-type:
    default: gre
    type: string
    description: |
      Overlay network type to use choose one of:
      .
        gre
        vxlan 
      .
  # HA configuration settings
  vip:
    type: string
    default:
    description: |
      Virtual IP(s) to use to front API services in HA configuration.
      .
      If multiple networks are being used, a VIP should be provided for each
      network, separated by spaces.
  vip_iface:
    type: string
    default: eth0
    description: |
      Default network interface to use for HA vip when it cannot be automatically
      determined.
  vip_cidr:
    type: int
    default: 24
    description: |
      Default CIDR netmask to use for HA vip when it cannot be automatically
      determined.
  ha-bindiface:
    type: string
    default: eth0
    description: |
      Default network interface on which HA cluster will bind to communication
      with the other members of the HA Cluster.
  ha-mcastport:
    type: int
    default: 5424
    description: |
       Default multicast port number that will be used to communicate between
       HA Cluster nodes.
  debug:
    default: False
    type: boolean
    description: Enable debug logging
  verbose:
    default: False
    type: boolean
    description: Enable verbose logging
  # Network configuration options
  # by default all access is over 'private-address'
  os-admin-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Admin network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for admin endpoints.
  os-internal-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Internal network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for internal endpoints.
  os-public-network:
    type: string
    default:
    description: |
      The IP address and netmask of the OpenStack Public network (e.g.,
      192.168.0.0/24)
      .
      This network will be used for public endpoints.
  ssl_cert:
    type: string
    default:
    description: |
      SSL certificate to install and use for API ports.  Setting this value
      and ssl_key will enable reverse proxying, point Neutron's entry in the
      Keystone catalog to use https, and override any certficiate and key
      issued by Keystone (if it is configured to do so).
  ssl_key:
    type: string
    default:
    description: SSL key to use with certificate specified as ssl_cert.
  ssl_ca:
    type: string
    default:
    description: |
      SSL CA to use with the certificate and key provided - this is only
      required if you are providing a privately signed ssl_cert and ssl_key.
  l2-population:
    type: boolean
    default: True
    description: |
      Populate the forwarding tables of virtual switches (LinuxBridge or OVS),
      to decrease broadcast traffics inside the physical networks fabric while
      using overlays networks (VXLan, GRE).
  prefer-ipv6:
    type: boolean
    default: False
    description: |
      If True enables IPv6 support. The charm will expect network interfaces
      to be configured with an IPv6 address. If set to False (default) IPv4
      is expected.
      .
      NOTE: these charms do not currently support IPv6 privacy extension. In
      order for this charm to function correctly, the privacy extension must be
      disabled and a non-temporary address must be configured/available on
      your network interface.
  worker-multiplier:
    type: int
    default: 2
    description: |
      The CPU core multiplier to use when configuring worker processes for
      Neutron.  By default, the number of workers for each daemon is set to
      twice the number of CPU cores a service unit has.
  # VMware NSX plugin configuration
  nsx-controllers:
    type: string
    default:
    description: Space delimited addresses of NSX controllers
  nsx-username:
    type: string
    default: admin
    description: Username to connect to NSX controllers with
  nsx-password:
    type: string
    default: admin
    description: Password to connect to NSX controllers with
  nsx-tz-uuid:
    type: string
    default:
    description: |
      This is uuid of the default NSX Transport zone that will be used for
      creating tunneled isolated Quantum networks.  It needs to be created
      in NSX before starting Quantum with the nsx plugin.
  nsx-l3-uuid:
    type: string
    default:
    description: |
      This is uuid of the default NSX L3 Gateway Service.
  # end of NSX configuration
  # midonet-plugin configuration
  controller-ip:
    type: string
    default: "192.168.8.84"
    description: Space delimited addresses of controller
  midonet-username:
    type: string
    default: midonet
    description: Username for  midonet-agent
  midonet-password:
    type: string
    default: password
    description: Password for  midonet-agent
  midonet-projectid:
    type: string
    default: admin
    description: |
      This is midonet administrative user's tenant.
  # end of midonet-plugin configuration
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe-external-master subordinate charm.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
